# ATOM_TYPE: Type C
"""
What: Gemini API 评分器（主力）
Why: 快速、免费的云端 AI 评分
When: UniformMap v2.0 AI 评分层
Where: UniformMap/modules/inference/openrouter_scorer.py
Who: Antigravity Agent
How: from modules.inference.openrouter_scorer import OpenRouterScorer
"""
from _core.flow.atomic_flow import atomic_flow
import json
import logging
import google.generativeai as genai

class OpenRouterScorer:
    """Gemini API 评分器（主力引擎）"""
    
    @atomic_flow
    def __init__(
        self, 
        api_key: str = None,
        model: str = "gemini-2.0-flash-exp"
    ):
        # 使用 Gemini API
        self.api_key = api_key or _read_api_key("POTENTIAL_GOOGLE")
        genai.configure(api_key=self.api_key)
        self.model = genai.GenerativeModel(model)
        self.logger = logging.getLogger("GeminiScorer")
    
    async def score_prompt_async(self, prompt: str) -> dict:
        """異步評分單個 Prompt"""
        system_prompt = """你是專業的 AI 生成圖片評審。請根據視覺美感、執行度、細節評分 (0-10)。輸出 JSON 格式: {"score": 8.5, "reasoning": "..."}"""
        user_prompt = f"{system_prompt}\n\n請評分以下 Prompt：\n{prompt}"
        
        try:
            # 使用異步調用
            response = await self.model.generate_content_async(user_prompt)
            content = response.text
            
            # 徹底清理 JSON 中的控制字符 (例如換行符在字串內)
            import re
            clean_content = content.replace("```json", "").replace("```", "").strip()
            # 移除 JSON 塊外的多餘文字，只保留 {} 內容
            json_match = re.search(r'(\{.*\})', clean_content, re.DOTALL)
            if json_match:
                json_str = json_match.group(1)
                # 關鍵修正：處理特殊的控制字符
                json_str = re.sub(r'[\x00-\x1F\x7F]', '', json_str)
                return json.loads(json_str)
            return {"score": 5.0, "reasoning": f"找不到 JSON"}
        except Exception as e:
            self.logger.error(f"❌ Gemini 異步調用失敗: {e}")
            return {"score": 0.0, "reasoning": str(e)}
    

if __name__ == "__main__":
    import asyncio

# ============================================================================
# API Key Reader (Auto-generated by APIKeyScanner)
# ============================================================================

@atomic_flow
def _read_api_key(key_name: str) -> str:
    """
    從 APIkeyBase.md 讀取 API key
    
    Args:
        key_name: API key 的變數名稱（如 'GOOGLE_API_KEY'）
        
    Returns:
        API key 的實際值
        
    Raises:
        ValueError: 如果找不到對應的 key
    """
    import re
    from pathlib import Path
    
    # 動態定位 APIkeyBase.md
    base_path = Path(__file__).resolve().parents[4] / "Docs/Standards/Credentials/APIkeyBase.md"
    
    if not base_path.exists():
        raise FileNotFoundError(f"APIkeyBase.md not found at {base_path}")
    
    content = base_path.read_text(encoding='utf-8')
    
    # 匹配表格行: | key_name | `actual_value` | category |
    pattern = r'\|\s*' + re.escape('{key_name}').replace('{key_name}', r'{re.escape(key_name)}') + r'\s*\|\s*`([^`]+?)`\s*\|'
    match = re.search(pattern.format(key_name=key_name), content, re.IGNORECASE)
    
    if match:
        return match.group(1).strip()
    else:
        raise ValueError(f"API key '{key_name}' not found in APIkeyBase.md")

# ============================================================================

    async def test():
        logging.basicConfig(level=logging.INFO)
        scorer = OpenRouterScorer()
        print("🧪 正在測試異步評分器...")
        result = await scorer.score_prompt_async("a beautiful sunset over the mountains")
        print(f"✅ 測試結果: {result}")
    
    asyncio.run(test())